### ISSUE TITLE
Rename the SDK assembly to something simpler

### ISSUE THREAD

**Issue by Lamparter** [WindowsAppCommunity/WindowsAppCommunity.Sdk#11]
`WinAppCommunity.Sdk` is quite a long name, and the extension `Sdk` is not exactly necessary (if it's being installed from NuGet that's probably implied)
I think it would be better to rename the package to `WinAppCommunity`, `WindowsAppCommunity` or (my favourite) `CommunityInfrastructure` (mimics the WCT namespace and also similar to the #community-infra channel in the server.

**Comment by Arlodotexe** [comment]
The SDK assembly name _does_ need updating, but maybe not in the way you're thinking. It should match our organization name, so it should be `WindowsAppCommunity.Sdk`, loosely aligning with the naming scheme used by the nuget package `Microsoft.WindowsAppSDK`. 

We want the namespace and package name to clearly illustrate who is publishing the content, in this case by the Staff team in the Windows App Community.

**Comment by Lamparter** [comment]
Why not just WindowsAppCommunity?
